name: Deploy to GH Pages
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Test and Build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 13

      # Check out current repository
      - uses: actions/checkout@v3

      # Validate wrapper
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.0.3

      # Build application
      - name: Build
        run: ./gradlew build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: 'build/distributions'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
